# Generated by Django 3.0.6 on 2020-06-18 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='place',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='voiture',
        ),
        migrations.DeleteModel(
            name='Occupation',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
