# Generated by Django 3.0.6 on 2020-05-07 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('nb_places', models.IntegerField()),
                ('nb_etages', models.IntegerField()),
                ('heure_d_ouverture', models.TimeField()),
                ('heure_d_fermeture', models.TimeField()),
                ('prix', models.IntegerField()),
                ('unite_horaire', models.CharField(choices=[('H', '1 Hour'), ('30MINS', '30 Mins'), ('15MINS', '15 Mins')], max_length=30)),
                ('adresse', models.CharField(max_length=30)),
                ('securise', models.BooleanField(default=False)),
                ('barriere_auto', models.BooleanField(default=False)),
                ('couvert', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_etage', models.IntegerField()),
                ('num_zone', models.CharField(max_length=10)),
                ('is_occupied', models.BooleanField(default=False)),
                ('parking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Parking')),
            ],
        ),
    ]
