# Generated by Django 3.0.6 on 2020-06-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='parking_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
