# Generated by Django 3.0.6 on 2020-05-30 12:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='jours_d_ouverture',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(default=False), default=[True, True, True, True, True, True, True], size=8),
        ),
    ]
