# Generated by Django 3.0.6 on 2020-06-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_parking_parking_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='prix',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
