# Generated by Django 3.0.6 on 2020-06-18 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200618_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isCompleted', models.BooleanField(default=False)),
                ('date_debut', models.DateTimeField(auto_now=True)),
                ('date_fin', models.DateTimeField()),
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Place')),
                ('voiture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Voiture')),
            ],
        ),
    ]
