# Generated by Django 3.0.6 on 2020-05-30 12:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200530_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='jours_d_ouverture',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(default=False), default=list, null=True, size=8),
        ),
    ]
