# Generated by Django 3.0.6 on 2020-05-07 23:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_parking_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Place')),
            ],
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('reservation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Reservation')),
                ('isCompleted', models.BooleanField(default=False)),
                ('date_debut', models.DateTimeField(auto_now=True)),
                ('date_fin', models.DateTimeField()),
            ],
            bases=('api.reservation',),
        ),
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=30)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='voiture',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Voiture'),
        ),
    ]
