# Generated by Django 3.0.6 on 2020-05-10 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200507_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parkings', to=settings.AUTH_USER_MODEL),
        ),
    ]
