# Generated by Django 3.0.6 on 2020-05-30 12:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200530_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='jours_d_ouverture',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(default=False), blank=True, default=list, null=True, size=8),
        ),
    ]
