# Generated by Django 3.0.6 on 2020-06-18 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_occupation'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='num_place',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='occupation',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Place'),
        ),
        migrations.AlterField(
            model_name='occupation',
            name='voiture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Voiture'),
        ),
    ]
