# Generated by Django 3.0.6 on 2020-05-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_parking_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='name_parking',
            field=models.CharField(default='Parking', max_length=30),
        ),
        migrations.AddField(
            model_name='parking',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='parking',
            name='adresse',
            field=models.CharField(max_length=80),
        ),
    ]
