# Generated by Django 3.0.6 on 2020-06-19 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200618_2242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='num_zone',
            new_name='zone',
        ),
        migrations.AlterField(
            model_name='occupation',
            name='date_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='parking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Parking'),
        ),
    ]
