# Generated by Django 3.0.6 on 2020-05-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200527_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='WC',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parking',
            name='lavage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parking',
            name='telepeage',
            field=models.BooleanField(default=False),
        ),
    ]
