# Generated by Django 3.0.6 on 2020-06-23 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200623_2050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isConsulted', models.BooleanField(default=False)),
                ('t_parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Parking')),
                ('t_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
