# Generated by Django 3.0.6 on 2020-05-28 13:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200528_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='jours_d_ouverture',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(default=False), default=list, size=8),
        ),
    ]
