# Generated by Django 3.0.6 on 2020-06-23 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='t_car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Voiture'),
            preserve_default=False,
        ),
    ]
